### ISSUE TITLE
Replace C asserts

### ISSUE THREAD

**Issue by Capital-Asterisk** [Capital-Asterisk/longeronpp#4]
A common solution to this seems to be a custom assert macro.

**Comment by jonesmz** [comment]
For a lot of situations you'd want to use a macro that triggers the assembly instruction that activates a breakpoint in the debugger. I don't remember which one it is, but it has a 3 in it :-).

Generally you'll also want to trace out to the appropriate logging solution that the assert failed as well.

**Comment by jonesmz** [comment]
Actually, I think there are compiler intrinsics for doing the "activate breakpoint here" concept.
So i would recommend using *that* instead of calling out to inline assembly.

**Comment by Capital-Asterisk** [comment]
I can't find much information on these, neither do they sound portable. Anyways, I'll just go with the customizable macro that defaults to c assert, but can be plugged into a more advanced assert library if needed.
