### ISSUE TITLE
What's the license for this repository?

### ISSUE THREAD

**Issue by StellaSmith** [Capital-Asterisk/longeronpp#6]

**Comment by Capital-Asterisk** [comment]
The code is under the MIT license though SPDX headers, though I'll add the LICENSE file now.

**Comment by StellaSmith** [comment]
Could you add the LICENSE file to the 0.1.0 version too?

**Comment by Capital-Asterisk** [comment]
I'll make a new tagged release v0.1.1. I recently fixed a few major bugs; for example, trying to iterate an empty HierarchicalBitset would throw an exception :P

**Comment by StellaSmith** [comment]
Oh, even better then.
